#!/usr/bin/env python
"""Publish a trained scorer into the model registry.

    python scripts/publish_model.py --version 0.1.0

Trains the registry configuration, calibrates it on the calibration split,
scores it on test across several seeds, exports and parity-verifies the ONNX
artifact, then writes ``manifest.json``, the model, and a model card into
``src/scamvet_riskengine/models/<name>/<version>/``.

The model card is generated rather than written by hand, so it cannot drift
from the numbers that produced it. It states the corpus limitations as
prominently as the headline metric, because the most important thing a reader
needs to know about this model is what its evaluation does not establish.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from scamvet_riskengine.eval import metrics as m
from scamvet_riskengine.eval.aggregate import as_dict, summarise
from scamvet_riskengine.features.featurize import LexicalFeaturizer
from scamvet_riskengine.features.url import FEATURE_SPEC_VERSION
from scamvet_riskengine.models import build_calibrator
from scamvet_riskengine.models.boosted import BoostedConfig, boosted_scores, build_xgboost
from scamvet_riskengine.models.onnx_export import export_and_verify
from scamvet_riskengine.registry.manifest import Manifest, Thresholds

DEFAULT_FEATURES = Path("data/derived/url_features.parquet")
DEFAULT_REGISTRY = Path("src/scamvet_riskengine/models")
MODEL_NAME = "url-scorer-lexical"
META_COLUMNS = ["url", "type", "label", "group", "split"]
CARD_TEMPLATE = """# Model card: {name} {version}

Generated by `scripts/publish_model.py` on {trained_at}. Every figure here is
reproduced by that script from the committed corpus build; nothing is
hand-entered.

## What it does

Scores a URL for the likelihood that it is malicious, using lexical features
only: no network calls, no enrichment, no clocks. That is what lets the same
artifact serve the online path and the offline degradation path required by
ADR-004.

- Feature spec: `{feature_spec}` ({n_features} columns)
- Model: XGBoost {n_estimators} x depth {max_depth}
- Calibration: {calibration_method}
- Artifact: {artifact} ({size_kb} KB ONNX), parity to native within {parity:.1e}
- Track: product. Trains only on the CC0 corpus (LEGAL.md row C4), per ADR-007.

## Headline metric

**Phishing recall at 5% false-positive rate: {phishing_recall}**

Measured on the benign-vs-phishing view of the test split: {phishing_rows:,}
rows at a {phishing_base:.2%} positive rate. Figures are the mean and observed
range across seeds {seeds}; a difference smaller than the seed spread is not a
finding (ADR-009).

| metric | value |
|---|---|
| phishing recall @ FPR 5% | {phishing_recall} |
| phishing recall @ FPR 1% | {phishing_recall_1} |
| phishing PR-AUC | {phishing_pr_auc} |
| phishing ECE | {phishing_ece} |
| aggregate PR-AUC (all malicious classes) | {overall_pr_auc} |

The aggregate figure is reported for comparability and is **never the
headline**: the binary target mixes phishing with malware and defacement URLs,
which are structurally conspicuous and easy, and they dominate it.

## What this evaluation does not establish

Read this before quoting the number above.

**The corpus is a compilation, and some of its signal is provenance.** It was
assembled from five upstream sources with different collection methods. Three
features have been removed for encoding which file a row came from rather than
anything about the address: `had_scheme`, `scheme_is_https`, and the per-TLD
one-hot columns. Each removal *lowered* the reported score. A provenance audit
(`scripts/audit_provenance.py`) trains on nested feature subsets and finds that
performance on features whose meaning is intrinsic to the URL - brand, keyword,
entropy, structure signals - is **{floor}**, against {headline} on the full set.
Neither number transfers to production unchanged.

**The features built for this product's actual market barely fire here.**
`brand_domain_mismatch` is active in 0.44% of rows and `.in` domains are 0.26%,
because the corpus is Western and global while the brand list is India-tuned.
Those features are individually sharp - `brand_domain_mismatch` carries a 1.94x
lift where it fires - and collectively invisible at corpus scale. In the market
this product serves, that ratio inverts.

**Some labels are wrong.** The lowest-scoring "phishing" rows include ordinary
article URLs from established sites. Achievable recall is therefore capped
below 1.0 for reasons unrelated to modelling.

**The consequence.** Per ADR-006, the ML layer is not the primary evidence for
a consumer phishing verdict. Deterministic facts and the reasoning layer above
it carry more than originally planned, and the product metric is the Chapter B
golden set of real Indian scam artifacts scored by the full stack, not this
number.

## Thresholds

Thresholds are a property of the use case, not the model. All read the same
calibrated probability.

{threshold_table}

## Known false positives on legitimate Indian domains

The corpus contains almost no Indian sites - 0.26% of rows are `.in` - so the
model has never seen a legitimate Indian bank, and no aggregate metric measured
on a Western corpus can reveal what it does with one. The check below scores
every `official_domains` entry in the brand list, which are sites this project
itself asserts are real. **{n_flagged} of {n_checked} were flagged amber or red.**

{sanity_table}

Treat this as the honest ceiling on using the score alone. It is the concrete
form of the transfer problem described above, and the direct reason ADR-006
places deterministic facts and the reasoning layer above this model rather than
behind it.

## Intended use and limits

Intended: pre-verdict scoring inside ScamVet's layered stack, and offline
scoring when enrichment is unavailable.

Not intended: a standalone allow/deny gate, an authority on any specific site,
or use outside the layered verdict architecture. A red band is a risk
assessment, not an accusation.

## Provenance

- Corpus: {corpus} (licence row {licence_row}, see LEGAL.md)
- Trained: {trained_at}
- Commit: {git_sha}
- Splits grouped by registered domain; no eTLD+1 appears in more than one split
"""


def _sanity_check(target: Path, vet: Thresholds) -> dict[str, Any]:
    """Score the domains our own brand list asserts are legitimate.

    This is the false-positive check that matters for this product. The corpus
    contains almost no Indian sites - 0.26% of rows are .in - so the model has
    never seen a legitimate Indian bank, and aggregate metrics measured on a
    Western corpus cannot reveal what it does with one. The brand list's
    official_domains are, by our own assertion, real. Anything flagged here is
    a false positive on the exact population the product serves.
    """
    from scamvet_riskengine.explain.reasons import load_templates  # noqa: F401
    from scamvet_riskengine.features.url import _brands  # noqa: PLC2701
    from scamvet_riskengine.registry.scorer import build_scorer

    urls = []
    for brand in _brands()["brands"]:
        for domain in brand["official_domains"]:
            urls.append(f"https://{domain}/")
    urls = sorted(set(urls))

    scorer = build_scorer(target)
    results = scorer.score_many(urls, use_case="vet")
    flagged: list[dict[str, Any]] = [
        {"url": r.url, "band": r.band, "probability": float(r.probability)}
        for r in results
        if r.band != "green"
    ]
    flagged.sort(key=lambda row: float(row["probability"]), reverse=True)
    lines = ["| domain | band | probability |", "|---|---|---|"]
    lines += [
        f"| `{row['url']}` | {row['band']} | {row['probability']:.4f} |" for row in flagged[:15]
    ]
    if not flagged:
        lines.append("| _none_ | | |")
    return {
        "n_checked": len(urls),
        "n_flagged": len(flagged),
        "flagged": flagged,
        "table": "\n".join(lines),
    }


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except Exception:
        return "unknown"


def _featurizer_env() -> dict[str, str]:
    """The library versions that decide what a feature value means.

    ``feature_spec_version`` pins our extraction logic. It does not pin
    tldextract's bundled public-suffix snapshot, which decides where eTLD+1
    boundaries fall - so num_subdomains, tld_length and brand_domain_mismatch
    can move under an unchanged spec string when that wheel is upgraded.
    Recorded so the drift is detectable rather than silent.
    """
    import platform

    import tldextract

    return {
        "tldextract": tldextract.__version__,
        "python": platform.python_version(),
        "recorded": "captured-at-publish",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--features", type=Path, default=DEFAULT_FEATURES)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--version", required=True, help="semantic version, e.g. 0.1.0")
    parser.add_argument("--seeds", nargs="+", type=int, default=[42, 1, 7])
    parser.add_argument("--audit", type=Path, default=Path("data/derived/provenance_audit.json"))
    args = parser.parse_args()

    data = pd.read_parquet(args.features)
    feature_columns = [c for c in data.columns if c not in META_COLUMNS]
    parts = {n: data[data["split"] == n] for n in ("train", "calibration", "test")}
    X = {n: p[feature_columns].to_numpy(dtype=np.float32) for n, p in parts.items()}
    y = {n: p["label"].to_numpy() for n, p in parts.items()}
    test = parts["test"].reset_index(drop=True)

    phishing_mask = test["type"].isin(["benign", "phishing"]).to_numpy()
    y_phishing = (test["type"].to_numpy()[phishing_mask] == "phishing").astype(int)

    print(f"[1/5] training across seeds {args.seeds}")
    config = BoostedConfig(seed=args.seeds[0])
    overall_runs, phishing_runs = [], []
    model = calibrator = None
    for seed in args.seeds:
        seeded = BoostedConfig(
            n_estimators=config.n_estimators, max_depth=config.max_depth, seed=seed
        )
        candidate = build_xgboost(seeded, y["train"])
        candidate.fit(X["train"], y["train"])
        cal = build_calibrator("platt")
        cal.fit(boosted_scores(candidate, X["calibration"]), y["calibration"])
        probs = cal.predict_proba(boosted_scores(candidate, X["test"]))
        overall_runs.append(m.evaluate(y["test"], probs))
        phishing_runs.append(m.evaluate(y_phishing, probs[phishing_mask]))
        if model is None:  # the published artifact comes from the first seed
            model, calibrator = candidate, cal

    overall = summarise(overall_runs)
    phishing = summarise(phishing_runs)
    if model is None or calibrator is None:  # pragma: no cover - --seeds is validated above
        raise SystemExit("no model was trained; --seeds must not be empty")
    print(f"      phishing R@FPR5% {phishing['recall_at_fpr_0.05'].format()}")

    print("[2/5] exporting and verifying ONNX")
    target = args.registry / MODEL_NAME / args.version
    target.mkdir(parents=True, exist_ok=True)
    blob, export = export_and_verify(model, X["test"][:5000], path=target / "model.onnx")
    print(f"      {export.size_bytes / 1024:.1f} KB, parity {export.max_abs_parity_diff:.2e}")
    native_json = target / "model.json"
    model.get_booster().save_model(str(native_json))
    native_bytes = native_json.read_bytes()
    (target / "model.json.gz").write_bytes(gzip.compress(native_bytes, 9))
    native_json.unlink()
    print(
        f"      native model {len(native_bytes) / 1024:.0f} KB -> "
        f"{(target / 'model.json.gz').stat().st_size / 1024:.0f} KB gzipped"
    )

    print("[3/5] writing manifest")
    reference = phishing_runs[0]
    thresholds = {
        # Consumer verdict: precision-leaning, because a false red destroys
        # trust in a way a false amber does not.
        "vet": Thresholds(
            red=float(reference.threshold_at_fpr["0.01"]),
            amber=float(reference.threshold_at_fpr["0.05"]),
        ),
        # Pre-payment QR check: recall-leaning, since warning before money
        # moves is cheap and missing is not.
        "qr": Thresholds(
            red=float(reference.threshold_at_fpr["0.05"]),
            amber=float(reference.threshold_at_fpr["0.05"]) * 0.6,
        ),
    }
    featurizer = LexicalFeaturizer.from_dict(
        json.loads(Path("data/derived/featurizer.json").read_text())
    )
    manifest = Manifest(
        name=MODEL_NAME,
        version=args.version,
        track="product",
        corpus="Malicious URLs dataset (651,191 rows, CC0 1.0)",
        corpus_licence_row="C4",
        trained_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        git_sha=_git_sha(),
        feature_spec_version=FEATURE_SPEC_VERSION,
        featurizer=featurizer.to_dict(),
        featurizer_env=_featurizer_env(),
        model={
            "family": "xgboost",
            "config": config.as_dict(),
            "artifact": "model.onnx",
            "sha256": hashlib.sha256(blob).hexdigest(),
            "size_bytes": export.size_bytes,
            "parity_max_abs_diff": export.max_abs_parity_diff,
            "native_artifact": "model.json",
            "native_artifact_gzipped": True,
        },
        calibration={"method": "platt", **calibrator.to_dict()},
        thresholds=thresholds,
        metrics={
            "seeds": args.seeds,
            "phishing_view_rows": int(phishing_mask.sum()),
            "phishing_view_base_rate": float(y_phishing.mean()),
            "phishing": as_dict(phishing),
            "overall": as_dict(overall),
        },
        requires_network=False,
        model_card="MODEL_CARD.md",
    )
    manifest.write(target / "manifest.json")

    print("[4/5] checking known-legitimate domains")
    sanity = _sanity_check(target, thresholds["vet"])
    for row in sanity["flagged"][:5]:
        print(f"      FLAGGED {row['band']:>5} p={row['probability']:.4f}  {row['url']}")
    print(
        f"      {sanity['n_flagged']} of {sanity['n_checked']} official brand domains "
        f"flagged amber or red"
    )

    print("[5/5] writing model card")
    floor = headline = "not measured"
    if args.audit.is_file():
        audit = json.loads(args.audit.read_text())
        subsets = audit["subsets"]
        floor = f"{subsets['semantic_only']['phishing']['recall_at_fpr_0.05']['mean']:.3f}"
        headline = f"{subsets['all']['phishing']['recall_at_fpr_0.05']['mean']:.3f}"

    threshold_table = "\n".join(
        ["| use case | red at | amber at |", "|---|---|---|"]
        + [f"| {k} | {v.red:.4f} | {v.amber:.4f} |" for k, v in thresholds.items()]
    )
    card = CARD_TEMPLATE.format(
        name=MODEL_NAME,
        version=args.version,
        trained_at=manifest.trained_at,
        feature_spec=FEATURE_SPEC_VERSION,
        n_features=len(feature_columns),
        n_estimators=config.n_estimators,
        max_depth=config.max_depth,
        calibration_method="Platt (sigmoid)",
        artifact="model.onnx",
        size_kb=round(export.size_bytes / 1024, 1),
        parity=export.max_abs_parity_diff,
        phishing_recall=phishing["recall_at_fpr_0.05"].format(),
        phishing_recall_1=phishing["recall_at_fpr_0.01"].format(),
        phishing_pr_auc=phishing["pr_auc"].format(),
        phishing_ece=phishing["ece"].format(),
        overall_pr_auc=overall["pr_auc"].format(),
        phishing_rows=int(phishing_mask.sum()),
        phishing_base=float(y_phishing.mean()),
        seeds=args.seeds,
        floor=floor,
        headline=headline,
        threshold_table=threshold_table,
        sanity_table=sanity["table"],
        n_flagged=sanity["n_flagged"],
        n_checked=sanity["n_checked"],
        corpus=manifest.corpus,
        licence_row=manifest.corpus_licence_row,
        git_sha=manifest.git_sha,
    )
    (target / "MODEL_CARD.md").write_text(card, encoding="utf-8")

    print(f"      published {MODEL_NAME} {args.version} to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
